trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'your-azure-subscription'
  resourceGroup: 'your-resource-group'
  appName: 'sri-laxmi-alankar'
  storageAccountName: 'yourstorageaccountname'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: AzureFileCopy@4
  inputs:
    SourcePath: 'build/'
    azureSubscription: '$(azureSubscription)'
    Destination: 'AzureBlob'
    storage: '$(storageAccountName)'
    ContainerName: '$web'
    outputStorageUri: 'storageAccountUri'
    outputStorageContainerSasToken: 'sasToken'
    sasTokenTimeOutInMinutes: '240'
